spring:
  application:
    name: gateway-server
  config:
    import: nacos:gateway-server-dev.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: 56c7fa93-47cc-4635-86bd-ec095e0af244
        group: A_GROUP
        service: ${spring.application.name}
      config:
        namespace: 56c7fa93-47cc-4635-86bd-ec095e0af244
        group: A_GROUP
        prefix: ${spring.application.name}
        file-extension: yml
  profiles:
    active: dev #多环境配置
#        =======nacos=========
#server:
#  port: 80
#spring:
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      password:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true #开启动态路由
#gateway:
##  white-list:
##    -  /doLogin #登录
##    -  /free #免登录